### ISSUE TITLE
Unable to update builds using esphome version 2026.9.0

### ISSUE THREAD

**Issue by FirstRulez** [CSchlipp/espoolbuddy#28]
Not sure if I've done something to break my setup but I don't think so. I am having some issues updating my scale since my esphome docker updated to 2026.9.0.

This is happening for both my console and scale

```
[4/81] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bambuddy_api/bambuddy_api.cpp.obj
FAILED: [code=1] esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bambuddy_api/bambuddy_api.cpp.obj
ccache /cache/idf/tools/xtensa-esp-elf/esp-14.2.0_20260121/xtensa-esp-elf/bin/xtensa-esp32s3-elf-g++ @esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bambuddy_api/bambuddy_api.cpp.obj.rsp -MD -MT esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bambuddy_api/bambuddy_api.cpp.obj -MF esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bambuddy_api/bambuddy_api.cpp.obj.d -o esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bambuddy_api/bambuddy_api.cpp.obj -c /data/build/espoolbuddy-scale/src/esphome/components/bambuddy_api/bambuddy_api.cpp
../src/esphome/components/bambuddy_api/bambuddy_api.cpp:9:10: fatal error: esp_tls.h: No such file or directory
    9 | #include "esp_tls.h"
      |          ^~~~~~~~~~~
compilation terminated.
[11/81] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/esphome/ota/ota_esphome.cpp.obj
ninja: build stopped: subcommand failed.
Compilation failed because bambuddy_api.cpp (in "src" component) includes esp_tls.h, provided by esp-tls component(s).
However, esp-tls component(s) is not in the requirements list of "src".
To fix this, add esp-tls to PRIV_REQUIRES list of idf_component_register call in /data/build/espoolbuddy-scale/src/CMakeLists.txt.
```
Please let me know if you need any more details or me to do anything specific to help narrow this down.

**Comment by CSchlipp** [comment]
There was apparently a breaking change in esphome 2026.9. Should be fixed now.

**Comment by FirstRulez** [comment]
Thank you, confirmed it's sorted
